public class Employee {
    private int id;  // Keeps the id field for database use (auto-generated by the database)
    private String name;
    private String position;
    private double salary;

    // Constructor that accepts id, name, position, and salary
    public Employee(int id, String name, String position, double salary) {
        this.id = id;  // id is typically auto-generated in the database, but you can set it here if needed
        this.name = name;
        this.position = position;
        this.salary = salary;
    }

    // Getters for the fields (you can keep them if needed)
    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getPosition() {
        return position;
    }

    public double getSalary() {
        return salary;
    }

    // toString method to display employee information
    @Override
    public String toString() {
        return "Employee [ID=" + id + ", Name=" + name + ", Position=" + position + ", Salary=" + salary + "]";
    }
}